/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FormCreate: typeof import('./src/components/form-create.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VantForm: typeof import('./src/components/vant-form.vue')['default']
  }
}
