export function getPeriodMenu() {
  return Promise.resolve({
    code: 200,
    success: true,
    data: [
      {
        id: "1473191287278960642",
        parentId: "0",
        code: "period",
        name: "食安管理",
        alias: "食安管理",
        path: "/period",
        source: "bw-icon  icon-foodsafe",
        sort: 2,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: "",
        isDeleted: 0,
        children: [
          {
            id: "1473556876338012161",
            parentId: "1473191287278960642",
            code: "period:standard",
            name: "标准效期",
            alias: "menu",
            path: "/period/standard",
            source: "bw-icon  icon-period-standard",
            sort: 1,
            category: 1,
            action: 0,
            isOpen: 1,
            remark: "",
            isDeleted: 0,
            hasChildren: false,
            parentName: "",
            categoryName: "",
            actionName: "",
            isOpenName: "",
          },
          {
            id: "1754389628317601793",
            parentId: "1473191287278960642",
            code: "period:template",
            name: "模板管理",
            alias: "template",
            path: "/period/template",
            source: "bw-icon  icon-parameter",
            sort: 2,
            category: 1,
            action: 0,
            isOpen: 1,
            remark: "",
            isDeleted: 0,
            hasChildren: false,
            parentName: "",
            categoryName: "",
            actionName: "",
            isOpenName: "",
          },

        ],
        hasChildren: false,
        parentName: "",
        categoryName: "",
        actionName: "",
        isOpenName: "",
      },
      {
        id: "1473192010943201282",
        parentId: "0",
        code: "300",
        name: "业务审核",
        alias: "业务审核",
        path: "/audit/foodsafe",
        source: "bw-icon icon-audit1",
        sort: 3,
        category: 1,
        action: 0,
        isOpen: 1,
        remark: "",
        isDeleted: 0,
        children: [
          {
            id: "1473846452759699457",
            parentId: "1473192010943201282",
            code: "111",
            name: "效期审核",
            alias: "111",
            path: "/audit/foodsafe",
            source: "bw-icon  icon-rules",
            sort: 111,
            category: 1,
            action: 0,
            isOpen: 1,
            remark: "",
            isDeleted: 0,
            hasChildren: false,
            parentName: "",
            categoryName: "",
            actionName: "",
            isOpenName: "",
          },
        ],
        hasChildren: false,
        parentName: "",
        categoryName: "",
        actionName: "",
        isOpenName: "",
      },
    ],
    msg: "操作成功",
  });
}
